### PR TITLE
Add possibility to parse untouched fontawesome css file

### PR DESCRIPTION
**Pull request by n0v1**
This pull request makes it possible to use the untouched, uglified [Font Awesome css file]( https://github.com/FortAwesome/Font-Awesome/blob/master/web-fonts-with-css/css/fontawesome-all.min.css) for extracting the code points that are used by `nativescript-fonticon`. No more manual editing should be needed.

That permits to use webpack to copy the font files and css file from node_modules and use it directly.

I also added some unit tests. For easier isolatet testing, the mapCss function was moved to a separate module.

Also added linting and fixed some inconsistencies in code style.

Everything that worked before should still work.

image

### CODE REVIEW

**Comment by n0v1** [comment]
@NathanWalker friendly ping

**Comment by NathanWalker** [comment]
Very nice @n0v1 !! I’ve had notifications turned off awhile here, sorry for delay. Perhaps I could add you as contributor on the repo to have more control. This is amazing work 🙏
I merged another pr which introduced a conflict here. Possible to resolve?

**Comment by n0v1** [comment]
Will look at it in a few days, as I'm on holidays right now.
________________________________

**Comment by n0v1** [comment]
I rebased my changes to the current master branch. Should be good to merge.

**Comment by NathanWalker** [comment]
@n0v1 released in `2.0.0` now - thanks again 👍 🤗

**Pull request merged**
